Feat/#50
kc3hack/2024_H pull request #51
Opened 2024-03-21 03:16 UTC by aiueo-1234

Closes #50

2024-03-21 09:18 UTC, miyaji255 requested changes

2024-03-21 09:18 UTC, miyaji255 commented on README.md
> +https://github.com/kc3hack/2024_H/assets/130837816/5c99b093-9069-4e37-baad-d554c54bd982
動画タイトルが見えるのでもう少しいい感じにできませんか？
また、実際の速度ではなくイメージであることも追記してください。

2024-03-22 08:49 UTC, aiueo-1234 commented on README.md
> +https://github.com/kc3hack/2024_H/assets/130837816/5c99b093-9069-4e37-baad-d554c54bd982
動画サイズが大きすぎて、埋め込みだと読み込めないのでこうしてます。
420pに落としても無理だったので厳しいと思います。

2024-03-22 09:07 UTC, miyaji255 commented on README.md
> +https://github.com/kc3hack/2024_H/assets/130837816/5c99b093-9069-4e37-baad-d554c54bd982
アップロードするときのファイル名を変更すればいけませんかね？

2024-03-23 12:14 UTC, miyaji255 approved these changes

2024-03-23 12:15 UTC, merged